spring:
  application:
    name: nearbuddies
  data:
    mongodb:
      host: localhost
      port: 27017
      auto-index-creation: true
      database: nearbuddies_db
      authentication-database: admin
      username: root
      password: rootpassword
  mvc:
    async:
      request-timeout: 60000

server:
  port: 8080