package com.NearBuddies.backend.membership;

import com.NearBuddies.backend.user.UserDTO;

import java.util.Date;

public record MembershipDTO(
        String id,
        Date joinedAt,
        Date leftAt,
        boolean isActive,
        UserDTO user
) {
    // Constructors, getters, and other methods are automatically generated by the record
}